/* tslint:disable */
/* eslint-disable */
/**
 * Time Booking
 * Time Booking API for IMS
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: tobias.demmer@it-experts.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

